### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by avrilnoeme** [Rurikobaka/LEDE_quectel_SRPD_PCIE#1]
https://github.com/Rurikobaka/LEDE_quectel_SRPD_PCIE/blob/d9379527a7260ab522acc62aa9cc065e84538174/sipa_dummy.c#L440C3-L440C3
`&sipa_summy->napi,` 
thx

**Comment by Rurikobaka** [comment]
嗯？沒看懂甚麼意思…

**Comment by avrilnoeme** [comment]
&sipa_dummy->napi, 
![haha](https://github.com/Rurikobaka/LEDE_quectel_SRPD_PCIE/assets/9085763/f55cd55c-597f-40ba-beeb-8c42dcc5144e)

**Comment by Rurikobaka** [comment]
> &sipa_dummy->napi, 
> 
> ![haha](https://github.com/Rurikobaka/LEDE_quectel_SRPD_PCIE/assets/9085763/f55cd55c-597f-40ba-beeb-8c42dcc5144e)
> 
> 

看到了 之後改一下（）
